### ISSUE TITLE
Re: Problems with GeoIP localization

### ISSUE THREAD

**Issue by ualenet** [IssabelFoundation/security#6]
Problems with GeoIP localization.
In English, there are no problems with displaying the rules, as soon as the language of the panel changes to Bulgarian, for example, the firewall rule is not displayed
(The firewall does not have support for GeoIP Localization)

**Comment by ualenet** [comment]
I enabled repositories in the system (Beta RPM Repository for Issabel), and updated the system, it did not help

**Comment by asternic** [comment]
Thanks, its a problem with a multi line translation file in issabel-framework. Fixed for release 5 on the framework repository.
